name: AlphaVantage
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: John <email@example.com>

environment:
  sdk: '>=2.00.1 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.5.0
